### ISSUE TITLE
Party chat text too large and cut off

### ISSUE THREAD

**Issue by KiwifruitDev** [Vexcenot/-middle-mann#160]
**Fill these checkmarks before reporting a bug!**

- [x] i am not using any additional mods that might overwrite any hud files (things like portraits and stuff of the sort)

**Describe the Issue**
The party chat text is unreadable as it is far too large and gets cut off on the right side of the window.

**Steps To Reproduce (gamemode/loadout etc)**

1. Go to the main menu
1. Open party chat
1. Type in a message
1. Observe the larger text

**Expected behavior**
Party chat text should be smaller and not cut off.

**Screenshots**

<img width="379" height="500" alt="Image" src="https://github.com/user-attachments/assets/604a0473-807d-4293-beac-a762fa0cf7e0" />

**Desktop (please complete the following information):**

- OS [e.g. Windows 10, macOS 11.5, Ubuntu 20.04]: windows 11 25h2
- Resolution and Aspect Ratio [eg. 1280x960 4:3]: 1920x1080 16:9

**TF2 Specific Info (please complete the following information):**

- HUD Version: `-middlemann_03569.zip` middle mann v23.1.1 last updated : 30/03/25 

- Customizations Applied (if any, if none type "none"): none
- Other Mods in tf/custom? if so, which ones?: master hitmarkers, animated loading screen, mastercomfig ultra preset, custom viewmodels (no hud files)

**Comment by Vexcenot** [comment]
Hi, this has been fixed a long time ago. Please simply update middlemann to the latest version.

**Comment by KiwifruitDev** [comment]
> Hi, this has been fixed a long time ago. Please simply update middlemann to the latest version.

I did, I reinstalled from gamebanana

**Comment by KiwifruitDev** [comment]
Just confirmed that the latest commit on `master` e7f5e4505617eb0b9b42cf8a7cabd3d37563d18e continues to face this issue

<img width="384" height="502" alt="Image" src="https://github.com/user-attachments/assets/bc7151dc-03f3-49a9-9e43-17b10d81cba5" />

**Comment by KiwifruitDev** [comment]
I uninstalled all of my custom addons and the issue went away, so I reverted it and only removed middle mann but the issue remained.

Through trial and error, I removed [animated loading screen](https://gamebanana.com/mods/462858) and found it fixed the issue while also adding several new hud elements I've previously not seen in middle mann.

Therefore, this is not middle mann-related so I will close this issue, though I can't find an issues page for that addon.

@Vexcenot Mind if I ask since you are the developer of animated loading screen, is there a page where I could submit an issue like this to? Unless I might've configured something wrong on my end.

**Comment by tekunotri** [comment]
not hud's fault, this was fixed last year
https://github.com/Vexcenot/-middle-mann/blob/e7f5e4505617eb0b9b42cf8a7cabd3d37563d18e/resource/ui/globalchat.res#L18-L20
